/**
 * © 2025 CFH, All Rights Reserved
 * File: cache.ts
 * Path: C:\CFH\backend\config\cache.ts
 * Purpose: CFH Premium ++ Cache Handler (Redis) with logging and validation in the CFH Automotive Ecosystem.
 * Author: CFH Dev Team (generated by Cod1, reviewed by Grok)
 * Date: 2025-07-15 [1505]
 * Version: 1.0.0
 * Version ID: f0g1h2i3-j4k5-l6m7-n8o9-p0q1r2s3t4u5
 * Crown Certified: Yes (pending final test)
 * Batch ID: Compliance-071425
 * Artifact ID: f0g1h2i3-j4k5-l6m7-n8o9-p0q1r2s3t4u5
 * Save Location: C:\CFH\backend\config\cache.ts
 * Updated By: Grok (based on Cod1 suggestions)
 * Timestamp: 2025-07-15 [1505]
 */

/*
 * Future Enhancements (Cod1):
 * - Add advanced TTL strategies (e.g., sliding expiration) (Cod1, 2025-07-15 [1505]).
 * - Add segmented keys (e.g., premium:cache:key) (Cod1, 2025-07-15 [1505]).
 */

import Redis from 'ioredis';
import { z } from 'zod';
import logger from '@utils/logger'; // Alias import
import { v4 as uuidv4 } from 'uuid';

const redisUrl = process.env.REDIS_URL || 'redis://localhost:6379';

// Connection initialization
export const redisClient = new Redis(redisUrl);

redisClient.on('connect', () => logger.info('🔌 Redis connected'));
redisClient.on('error', (err) => logger.error('❌ Redis error:', { error: err, correlationId: uuidv4() }));

// Basic schema to validate JSON payloads (optional upgrade)
const CachePayloadSchema = z.record(z.any());

/**
 * Set value in Redis with optional TTL.
 * @param {string} key - Cache key.
 * @param {unknown} value - Value to cache.
 * @param {number} [ttlSeconds] - Optional TTL in seconds.
 */
export const setCache = async (
  key: string,
  value: unknown,
  ttlSeconds?: number
): Promise<void> => {
  const correlationId = uuidv4();
  try {
    const payload = JSON.stringify(value);
    if (ttlSeconds) {
      await redisClient.setex(key, ttlSeconds, payload);
    } else {
      await redisClient.set(key, payload);
    }
    logger.debug(`[CACHE SET] ${key}`, { correlationId });
  } catch (error) {
    logger.error(`[CACHE SET ERROR] ${key}:`, { error, correlationId });
  }
};

/**
 * Get and optionally validate cached data.
 * @param {string} key - Cache key.
 * @returns {T | null} Cached value or null.
 */
export const getCache = async <T = any>(key: string): Promise<T | null> => {
  const correlationId = uuidv4();
  try {
    const raw = await redisClient.get(key);
    if (!raw) return null;

    const parsed = JSON.parse(raw);
    const validated = CachePayloadSchema.safeParse(parsed);
    if (!validated.success) {
      logger.warn(`[CACHE INVALID SCHEMA] ${key}`, { correlationId });
      return null;
    }

    logger.debug(`[CACHE HIT] ${key}`, { correlationId });
    return validated.data as T;
  } catch (error) {
    logger.error(`[CACHE GET ERROR] ${key}:`, { error, correlationId });
    return null;
  }
};

/**
 * Invalidate (delete) cache key.
 * @param {string} key - Cache key.
 */
export const deleteCache = async (key: string): Promise<void> => {
  const correlationId = uuidv4();
  try {
    await redisClient.del(key);
    logger.debug(`[CACHE DELETE] ${key}`, { correlationId });
  } catch (error) {
    logger.error(`[CACHE DELETE ERROR] ${key}:`, { error, correlationId });
  }
};

// Premium/Wow++ Note: Add premium cache keys (e.g., premium:user:cache), Wow++ in-memory fallback (e.g., Map for offline).
