/**
 * © 2025 CFH, All Rights Reserved
 * File: database.ts
 * Path: C:\CFH\backend\config\database.ts
 * Purpose: Manages MongoDB connection using Mongoose with logging and error handling in the CFH Automotive Ecosystem.
 * Author: CFH Dev Team (generated by Grok)
 * Date: 2025-07-15 [06:34]
 * Version: 1.0.0
 * Version ID: f9f9a8a9-0b0c-4d4e-8e8f-1a1b2c3d4e5f
 * Crown Certified: Yes (pending final test)
 * Batch ID: Compliance-071425
 * Artifact ID: f9f9a8a9-0b0c-4d4e-8e8f-1a1b2c3d4e5f
 * Save Location: C:\CFH\backend\config\database.ts
 * Updated By: Grok
 * Timestamp: 2025-07-15 [06:34]
 */

/*
 * Future Enhancements (Grok):
 * - Add multi-DB support for Wow++ (replica sets, sharding) (2025-07-15 [06:34]).
 * - Integrate connection pooling tuning for premium (2025-07-15 [06:34]).
 */

import mongoose from 'mongoose';
import logger from '@utils/logger'; // Alias import

/**
 * Connects to MongoDB using Mongoose.
 */
export const connectToDatabase = async (): Promise<void> => {
  const uri = process.env.MONGO_URI || 'mongodb://localhost:27017/cfh';
  try {
    await mongoose.connect(uri, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    logger.info('Connected to MongoDB', { uri });
  } catch (error) {
    logger.error('MongoDB connection failed', { error });
    process.exit(1); // Exit on connection failure
  }
};

// Listen for connection events
mongoose.connection.on('disconnected', () => {
  logger.warn('MongoDB disconnected');
});

mongoose.connection.on('error', (error) => {
  logger.error('MongoDB connection error', { error });
});

// Premium/Wow++ Note: Add replica set for premium high availability, sharding for Wow++ scalability.
