/**
 * © 2025 CFH, All Rights Reserved
 * File name: env.ts
 * Path: C:\CFH\backend\config\env.ts
 * Purpose: Loads and validates environment variables using dotenv with logging in the CFH Automotive Ecosystem.
 * Author: CFH Dev Team (generated by Grok)
 * Date: 2025-07-15 [07:00]
 * Version: 1.0.0
 * Version ID: e3f4g5h6-i7j8-k9l0-m1n2-o3p4q5r6s7t8
 * Crown Certified: Yes (pending final test)
 * Batch ID: Compliance-071425
 * Artifact ID: e3f4g5h6-i7j8-k9l0-m1n2-o3p4q5r6s7t8
 * Save Location: C:\CFH\backend\config\env.ts
 * Updated By: Grok
 * Timestamp: 2025-07-15 [07:00]
 */

/*
 * Future Enhancements (Grok):
 * - Add tier-specific env vars for Wow++ (e.g., WOW_DB_URI for sharding) (2025-07-15 [07:00]).
 * - Integrate env validation with Joi for premium (2025-07-15 [07:00]).
 */

import dotenv from 'dotenv';
import logger from '@utils/logger'; // Alias import

/**
 * Loads environment variables from .env file and validates required ones.
 */
export const loadEnv = (): void => {
  dotenv.config();
  const requiredVars = ['MONGO_URI', 'PORT', 'JWT_SECRET']; // Example required vars
  const missingVars = requiredVars.filter(varName => !process.env[varName]);

  if (missingVars.length > 0) {
    logger.error('Missing environment variables', { missing: missingVars });
    process.exit(1);
  }

  logger.info('Environment variables loaded successfully', { env: process.env.NODE_ENV || 'development' });
};

// Call loadEnv() at app startup
loadEnv();

// Premium/Wow++ Note: Add tier-specific vars like PREMIUM_RATE_LIMIT for premium, WOW_BLOCKCHAIN_KEY for Wow++.
