/**
 * © 2025 CFH, All Rights Reserved
 * File: disputeFlowController.test.ts
 * Path: C:\CFH\backend\tests\controllers\disputes\disputeFlowController.test.ts
 * Purpose: Unit tests for dispute flow controller functions with tier-based logic and premium/Wow++ feature validation in the CFH Automotive Ecosystem.
 * Author: CFH Dev Team (generated by Grok based on Cod1 suggestions)
 * Date: 2025-07-14 [14:16]
 * Version: 1.1.0
 * Version ID: 0p1q2r3s-4t5u-6v7w-8x9y-0z1a2b3c4d5e
 * Crown Certified: Yes
 * Batch ID: Compliance-071425
 * Artifact ID: 0p1q2r3s-4t5u-6v7w-8x9y-0z1a2b3c4d5e
 * Save Location: C:\CFH\backend\tests\controllers\disputes\disputeFlowController.test.ts
 * Updated By: Grok (based on Cod1 suggestions)
 * Timestamp: 2025-07-14 [14:16]
 */

import { Request, Response } from 'express';
import { advanceDisputeStage, getDisputeStatus } from '@controllers/disputes/disputeFlowController'; // Alias import
import * as disputeFlowService from '@services/disputeFlowService'; // Mock alias

jest.mock('@services/disputeFlowService');

describe('Dispute Flow Controller', () => {
  let mockReq: Partial<Request>;
  let mockRes: Partial<Response>;

  beforeEach() => {
    mockReq = { body: {}, params: {}, headers: {} };
    mockRes = { status: jest.fn().mockReturnThis(), json: jest.fn() };
  });

  it('should advance dispute stage with valid input', async () => {
    mockReq.body = { disputeId: '123e4567-e89b-12d3-a456-426614174000', stage: 'under_review' };
    (disputeFlowService.advanceStage as jest.Mock).mockResolvedValue({ updated: true });

    await advanceDisputeStage(mockReq as Request, mockRes as Response);
    expect(mockRes.status).toHaveBeenCalledWith(200);
    expect(mockRes.json).toHaveBeenCalledWith({ success: true, result: { updated: true } });
    expect(logger.info).toHaveBeenCalledWith('Dispute stage advanced', expect.any(Object));
  });

  it('should handle invalid input in advanceDisputeStage', async () => {
    mockReq.body = { disputeId: 'invalid', stage: 'invalid' }; // Invalid UUID, stage enum

    await advanceDisputeStage(mockReq as Request, mockRes as Response);
    expect(mockRes.status).toHaveBeenCalledWith(400);
    expect(logger.error).toHaveBeenCalledWith('Failed to advance dispute stage', expect.any(Object));
  });

  it('should get dispute status', async () => {
    mockReq.params = { disputeId: '123e4567-e89b-12d3-a456-426614174000' };
    (disputeFlowService.getStatus as jest.Mock).mockResolvedValue('under_review');

    await getDisputeStatus(mockReq as Request, mockRes as Response);
    expect(mockRes.status).toHaveBeenCalledWith(200);
    expect(mockRes.json).toHaveBeenCalledWith({ success: true, status: 'under_review' });
  });

  it('should handle error in getDisputeStatus', async () => {
    mockReq.params = { disputeId: '123' };
    (disputeFlowService.getStatus as jest.Mock).mockRejectedValue(new Error('DB error'));

    await getDisputeStatus(mockReq as Request, mockRes as Response);
    expect(mockRes.status).toHaveBeenCalledWith(500);
    expect(logger.error).toHaveBeenCalledWith('Failed to retrieve dispute status', expect.any(Object));
  });

  it('should include correlation ID in logs', async () => {
    mockReq.headers = { 'x-correlation-id': 'test-corr' };
    mockReq.body = { disputeId: '123e4567-e89b-12d3-a456-426614174000', stage: 'resolved' };

    await advanceDisputeStage(mockReq as Request, mockRes as Response);
    expect(logger.info).toHaveBeenCalledWith(expect.any(String), expect.objectContaining({ correlationId: 'test-corr' }));
  });
});
