/**
 * © 2025 CFH, All Rights Reserved
 * File: lenderReputationService.ts
 * Path: C:\CFH\backend\services\lender\lenderReputationService.ts
 * Purpose: Service layer for lender reputation operations, separating logic from controller in the CFH Automotive Ecosystem.
 * Author: CFH Dev Team (generated by Grok based on Cod1 suggestions)
 * Date: 2025-07-15 [0634]
 * Version: 1.0.0
 * Version ID: a3b4c5d6-e7f8-g9h0-i1j2-k3l4m5n6o7p8
 * Crown Certified: Yes (pending final test)
 * Batch ID: Compliance-071425
 * Artifact ID: a3b4c5d6-e7f8-g9h0-i1j2-k3l4m5n6o7p8
 * Save Location: C:\CFH\backend\services\lender\lenderReputationService.ts
 * Updated By: Grok (based on Cod1 suggestions)
 * Timestamp: 2025-07-15 [0634]
 */

/*
 * Future Enhancements (Cod1):
 * - Add interfaces for Review and LenderReputation (Cod1, 2025-07-15 [09:00]).
 * - Use Zod for validation (rating 0-5, comment length) (Cod1, 2025-07-15 [09:00]).
 * - Replace console.error with @utils/logger (Cod1, 2025-07-15 [09:00]).
 * - Add rate limiting to prevent spam reviews (Cod1, 2025-07-15 [09:00]).
 * - Add authorization middleware (e.g., borrower interaction check) (Cod1, 2025-07-15 [09:00]).
 * - Refactor average rating calculation to function (Cod1, 2025-07-15 [09:00]).
 * - Add test coverage with ts-jest or vitest (Cod1, 2025-07-15 [09:00]).
 */

import LenderReputation from '@models/LenderReputation'; // Alias import

interface Review {
  reviewer: string;
  rating: number;
  comment: string;
}

interface LenderReputationInterface {
  lender: string;
  rating: number;
  reviews: Review[];
  updatedAt: Date;
}

export const getReputation = async (lenderId: string): Promise<LenderReputationInterface | null> => {
  return await LenderReputation.findOne({ lender: lenderId })
    .populate('lender', 'username email')
    .populate('reviews.reviewer', 'username');
};

export const addReview = async (lenderId: string, reviewerId: string, rating: number, comment: string): Promise<LenderReputationInterface> => {
  let reputation = await LenderReputation.findOne({ lender: lenderId });
  if (!reputation) {
    reputation = new LenderReputation({ lender: lenderId, reviews: [] });
  }

  reputation.reviews.push({ reviewer: reviewerId, rating, comment });
  reputation.rating = calculateAverageRating(reputation.reviews);
  reputation.updatedAt = new Date();

  await reputation.save();
  return reputation;
};

const calculateAverageRating = (reviews: Review[]): number => {
  if (reviews.length === 0) return 0;
  return reviews.reduce((sum, r) => sum + r.rating, 0) / reviews.length;
};
