/**
 * © 2025 CFH, All Rights Reserved
 * File: cache.test.ts
 * Path: C:\CFH\backend\tests\config\cache.test.ts
 * Purpose: Unit tests for cache.ts (Redis cache handler with premium/Wow++ features) in the CFH Automotive Ecosystem.
 * Author: CFH Dev Team (generated by Grok based on Cod1 suggestions)
 * Date: 2025-07-15 [1505]
 * Version: 1.0.0
 * Version ID: 2l3m4n5o-6p7q-8r9s-0t1u-2v3w4x5y6z7a
 * Crown Certified: Yes
 * Batch ID: Compliance-071425
 * Artifact ID: 2l3m4n5o-6p7q-8r9s-0t1u-2v3w4x5y6z7a
 * Save Location: C:\CFH\backend\tests\config\cache.test.ts
 * Updated By: Grok (based on Cod1 suggestions)
 * Timestamp: 2025-07-15 [1505]
 */

/*
 * Future Enhancements (Cod1):
 * - Add advanced TTL strategies (e.g., sliding expiration) (Cod1, 2025-07-15 [1505]).
 * - Add segmented keys (e.g., premium:cache:key) (Cod1, 2025-07-15 [1505]).
 */

import { redisClient, setCache, getCache, deleteCache } from '@config/cache'; // Alias import
import logger from '@utils/logger'; // Spy on logger

jest.mock('ioredis');

describe('Cache Config', () => {
  beforeEach() => {
    jest.clearAllMocks();
  });

  it('should set cache value without TTL', async () => {
    (redisClient.set as jest.Mock).mockResolvedValue(true);
    await setCache('key', { data: 'value' });
    expect(redisClient.set).toHaveBeenCalledWith('key', expect.any(String));
    expect(logger.debug).toHaveBeenCalledWith('[CACHE SET] key', expect.any(Object));
  });

  it('should set cache value with TTL', async () => {
    (redisClient.setex as jest.Mock).mockResolvedValue(true);
    await setCache('key', { data: 'value' }, 60);
    expect(redisClient.setex).toHaveBeenCalledWith('key', 60, expect.any(String));
    expect(logger.debug).toHaveBeenCalledWith('[CACHE SET] key', expect.any(Object));
  });

  it('should get cache value', async () => {
    (redisClient.get as jest.Mock).mockResolvedValue(JSON.stringify({ data: 'value' }));
    const result = await getCache('key');
    expect(result).toEqual({ data: 'value' });
    expect(logger.debug).toHaveBeenCalledWith('[CACHE HIT] key', expect.any(Object));
  });

  it('should return null on invalid schema', async () => {
    (redisClient.get as jest.Mock).mockResolvedValue('invalid');
    const result = await getCache('key');
    expect(result).toBeNull();
    expect(logger.warn).toHaveBeenCalledWith('[CACHE INVALID SCHEMA] key', expect.any(Object));
  });

  it('should delete cache value', async () => {
    (redisClient.del as jest.Mock).mockResolvedValue(true);
    await deleteCache('key');
    expect(redisClient.del).toHaveBeenCalledWith('key');
    expect(logger.debug).toHaveBeenCalledWith('[CACHE DELETE] key', expect.any(Object));
  });

  it('should handle error in setCache', async () => {
    (redisClient.set as jest.Mock).mockRejectedValue(new Error('Set error'));
    await setCache('key', { data: 'value' });
    expect(logger.error).toHaveBeenCalledWith('[CACHE SET ERROR] key:', expect.any(Object));
  });
});
