/**
 * © 2025 CFH, All Rights Reserved
 * File: database.test.ts
 * Path: C:\CFH\backend\tests\config\database.test.ts
 * Purpose: Unit tests for database connection config in the CFH Automotive Ecosystem.
 * Author: CFH Dev Team (generated by Grok)
 * Date: 2025-07-15 [06:34]
 * Version: 1.0.0
 * Version ID: 2w3x4y5z-6a7b-8c9d-0e1f-2g3h4i5j6k7l
 * Crown Certified: Yes
 * Batch ID: Compliance-071425
 * Artifact ID: 2w3x4y5z-6a7b-8c9d-0e1f-2g3h4i5j6k7l
 * Save Location: C:\CFH\backend\tests\config\database.test.ts
 * Updated By: Grok
 * Timestamp: 2025-07-15 [06:34]
 */

/*
 * Future Enhancements (Grok):
 * - Add multi-DB support for Wow++ (replica sets, sharding) (2025-07-15 [06:34]).
 * - Integrate connection pooling tuning for premium (2025-07-15 [06:34]).
 */

import mongoose from 'mongoose';
import { connectToDatabase } from '@config/database'; // Alias import
import logger from '@utils/logger'; // Spy on logger

jest.mock('mongoose');

describe('Database Config', () => {
  beforeEach() => {
    jest.clearAllMocks();
  });

  it('should connect to MongoDB', async () => {
    (mongoose.connect as jest.Mock).mockResolvedValue(true);
    await connectToDatabase();
    expect(mongoose.connect).toHaveBeenCalledWith(expect.any(String), expect.any(Object));
    expect(logger.info).toHaveBeenCalledWith('Connected to MongoDB', expect.any(Object));
  });

  it('should handle connection error', async () => {
    (mongoose.connect as jest.Mock).mockRejectedValue(new Error('Connection failed'));
    await expect(connectToDatabase).rejects.toThrow();
    expect(logger.error).toHaveBeenCalledWith('MongoDB connection failed', expect.any(Object));
  });

  it('should log disconnection event', () => {
    mongoose.connection.emit('disconnected');
    expect(logger.warn).toHaveBeenCalledWith('MongoDB disconnected');
  });

  it('should log connection error event', () => {
    mongoose.connection.emit('error', new Error('Error event'));
    expect(logger.error).toHaveBeenCalledWith('MongoDB connection error', expect.any(Object));
  });
});
