/**
 * © 2025 CFH, All Rights Reserved
 * File: env.test.ts
 * Path: C:\CFH\backend\tests\config\env.test.ts
 * Purpose: Unit tests for env.ts (environment config loading) in the CFH Automotive Ecosystem.
 * Author: CFH Dev Team (generated by Grok)
 * Date: 2025-07-15 [1438]
 * Version: 1.0.0
 * Version ID: 4k5l6m7n-8o9p-0q1r-2s3t-4u5v6w7x8y9z
 * Crown Certified: Yes
 * Batch ID: Compliance-071425
 * Artifact ID: 4k5l6m7n-8o9p-0q1r-2s3t-4u5v6w7x8y9z
 * Save Location: C:\CFH\backend\tests\config\env.test.ts
 * Updated By: Grok
 * Timestamp: 2025-07-15 [1438]
 */

/*
 * Future Enhancements (Grok):
 * - Add tier-specific env vars for Wow++ (e.g., WOW_DB_URI for sharding) (2025-07-15 [1438]).
 * - Integrate env validation with Joi for premium (2025-07-15 [1438]).
 */

import dotenv from 'dotenv';
import { loadEnv } from '@config/env'; // Alias import
import logger from '@utils/logger'; // Spy on logger

jest.mock('dotenv');

describe('Env Config', () => {
  beforeEach() => {
    jest.clearAllMocks();
    process.env = {}; // Reset env
  });

  it('should load env variables successfully', () => {
    process.env.MONGO_URI = 'test-uri';
    process.env.PORT = '3000';
    process.env.JWT_SECRET = 'secret';
    (dotenv.config as jest.Mock).mockReturnValue({ parsed: process.env });

    loadEnv();
    expect(logger.info).toHaveBeenCalledWith('Environment variables loaded successfully', expect.any(Object));
  });

  it('should exit on missing required env variables', () => {
    (dotenv.config as jest.Mock).mockReturnValue({ parsed: process.env });
    const exitMock = jest.spyOn(process, 'exit').mockImplementation(() => {});
    loadEnv();
    expect(logger.error).toHaveBeenCalledWith('Missing environment variables', expect.any(Object));
    expect(exitMock).toHaveBeenCalledWith(1);
  });
});
