/**
 * © 2025 CFH, All Rights Reserved
 * File: mail.test.ts
 * Path: C:\CFH\backend\tests\config\mail.test.ts
 * Purpose: CFH Test Suite for Premium Mail Service with queueing in the CFH Automotive Ecosystem.
 * Author: CFH Dev Team (generated by Cod1, reviewed by Grok)
 * Date: 2025-07-15 [1432]
 * Version: 1.0.0
 * Version ID: 5x6y7z8a-9b0c-1d2e-3f4g-5h6i7j8k9l0m
 * Crown Certified: Yes
 * Batch ID: Compliance-071425
 * Artifact ID: 5x6y7z8a-9b0c-1d2e-3f4g-5h6i7j8k9l0m
 * Save Location: C:\CFH\backend\tests\config\mail.test.ts
 * Updated By: Grok (based on Cod1 suggestions)
 * Timestamp: 2025-07-15 [1432]
 */

/*
 * Future Enhancements (Cod1):
 * - Add coverage report or e2e test with Supertest (Cod1, 2025-07-15 [1432]).
 */

import nodemailer from 'nodemailer';
import { sendMail, enqueueMail } from '@config/mail'; // Alias import
import logger from '@utils/logger'; // Spy on logger

jest.mock('nodemailer');

const mockSendMail = jest.fn();
(nodemailer.createTransport as jest.Mock).mockReturnValue({ sendMail: mockSendMail });

jest.spyOn(logger, 'info');
jest.spyOn(logger, 'warn');
jest.spyOn(logger, 'error');

describe('Mail Service', () => {
  beforeEach() => {
    jest.clearAllMocks();
  });

  it('should send email successfully', async () => {
    mockSendMail.mockResolvedValue(true);
    await sendMail({ to: 'user@example.com', subject: 'Hello', text: 'World' });

    expect(mockSendMail).toHaveBeenCalledWith(
      expect.objectContaining({ to: 'user@example.com', subject: 'Hello' })
    );
    expect(logger.info).toHaveBeenCalledWith(
      '📤 Email sent',
      expect.objectContaining({ to: 'user@example.com' })
    );
  });

  it('should validate schema and skip invalid email', async () => {
    await sendMail({ to: 'invalid-email', subject: '', text: '' } as any);

    expect(mockSendMail).not.toHaveBeenCalled();
    expect(logger.warn).toHaveBeenCalledWith(expect.stringContaining('📪 Invalid mail schema'), expect.anything());
  });

  it('should log error if sending fails', async () => {
    mockSendMail.mockRejectedValue(new Error('Fail'));
    await sendMail({ to: 'fail@example.com', subject: 'Oops', text: 'Boom' });

    expect(logger.error).toHaveBeenCalledWith(
      '📭 Email send failed',
      expect.objectContaining({ to: 'fail@example.com' })
    );
  });

  it('should enqueue mail stub (Wow++)', async () => {
    await enqueueMail({ to: 'queued@example.com', subject: 'Queued', text: 'Test' });
    expect(logger.info).toHaveBeenCalledWith(
      '[Queue:MAIL] Stub enqueued mail',
      expect.objectContaining({ to: 'queued@example.com' })
    );
  });
});
