/**
 * © 2025 CFH, All Rights Reserved
 * File: secrets.test.ts
 * Path: C:\CFH\backend\tests\config\secrets.test.ts
 * Purpose: Unit tests for secrets.ts (secrets loading and validation) in the CFH Automotive Ecosystem.
 * Author: CFH Dev Team (generated by Grok)
 * Date: 2025-07-15 [1445]
 * Version: 1.0.0
 * Version ID: 6g7h8i9j-0k1l-2m3n-4o5p-6q7r8s9t0u1v
 * Crown Certified: Yes
 * Batch ID: Compliance-071425
 * Artifact ID: 6g7h8i9j-0k1l-2m3n-4o5p-6q7r8s9t0u1v
 * Save Location: C:\CFH\backend\tests\config\secrets.test.ts
 * Updated By: Grok
 * Timestamp: 2025-07-15 [1445]
 */

/*
 * Future Enhancements (Grok):
 * - Add tier-specific secrets for Wow++ (e.g., WOW_BLOCKCHAIN_KEY) (2025-07-15 [1445]).
 * - Integrate secrets rotation for premium (2025-07-15 [1445]).
 */

import { loadSecrets } from '@config/secrets'; // Alias import
import logger from '@utils/logger'; // Spy on logger

describe('Secrets Config', () => {
  beforeEach() => {
    jest.clearAllMocks();
    process.env = {}; // Reset env
  });

  it('should load secrets successfully', () => {
    process.env.JWT_SECRET = 'test-secret';
    process.env.API_KEY = 'test-key';

    loadSecrets();
    expect(logger.info).toHaveBeenCalledWith('Secrets loaded successfully');
  });

  it('should exit on missing required secrets', () => {
    const exitMock = jest.spyOn(process, 'exit').mockImplementation(() => {});
    loadSecrets();
    expect(logger.error).toHaveBeenCalledWith('Missing secrets', expect.any(Object));
    expect(exitMock).toHaveBeenCalledWith(1);
  });
});
