/**
 * © 2025 CFH, All Rights Reserved
 * File Name: CaseBundleExporter.test.ts
 * Path: C:\CFH\backend\tests\disputes\CaseBundleExporter.test.ts
 * Purpose: Unit tests for dispute case export controller with tier-based logic in the CFH Automotive Ecosystem.
 * Author: CFH Dev Team (generated by Grok based on Cod1 suggestions)
 * Date: 2025-07-14 [14:16]
 * Version: 1.1.0
 * Version ID: y4z5a6b7-c8d9-e0f1-g2h3-i4j5k6l7m8n9
 * Crown Certified: Yes
 * Batch ID: Compliance-071425
 * Artifact ID: y4z5a6b7-c8d9-e0f1-g2h3-i4j5k6l7m8n9
 * Save Location: C:\CFH\backend\tests\disputes\CaseBundleExporter.test.ts
 * Updated By: Grok (based on Cod1 suggestions)
 * Timestamp: 2025-07-14 [14:16]
 */

import { Request, Response } from 'express';
import { exportCaseBundle } from '@controllers/disputes/CaseBundleExporter'; // Alias import
import DisputeCase from '@models/dispute/Dispute';
import archiver from 'archiver';

jest.mock('@models/dispute/Dispute');
jest.spyOn(archiver, 'create').mockImplementation(() => ({
  pipe: jest.fn(),
  append: jest.fn(),
  finalize: jest.fn(),
}));

describe('Case Bundle Exporter Controller', () => {
  let mockReq: Partial<Request>;
  let mockRes: Partial<Response>;

  beforeEach() => {
    mockReq = { headers: {} };
    mockRes = {
      setHeader: jest.fn(),
      status: jest.fn().mockReturnThis(),
      json: jest.fn(),
    };
  });

  it('should export ZIP with dispute cases', async () => {
    (DisputeCase.find as jest.Mock).mockResolvedValue([{ _id: '123', toJSON: () => ({ id: '123' }) }]);

    await exportCaseBundle(mockReq as Request, mockRes as Response);
    expect(mockRes.setHeader).toHaveBeenCalledWith('Content-Disposition', 'attachment; filename=dispute_cases.zip');
    expect(mockRes.setHeader).toHaveBeenCalledWith('Content-Type', 'application/zip');
    expect(logger.info).toHaveBeenCalledWith('Dispute cases exported successfully', expect.any(Object));
  });

  it('should return 404 if no cases found', async () => {
    (DisputeCase.find as jest.Mock).mockResolvedValue([]);

    await exportCaseBundle(mockReq as Request, mockRes as Response);
    expect(mockRes.status).toHaveBeenCalledWith(404);
    expect(mockRes.json).toHaveBeenCalledWith({ success: false, message: 'No cases found' });
  });

  it('should handle DB failure', async () => {
    (DisputeCase.find as jest.Mock).mockRejectedValue(new Error('DB error'));

    await exportCaseBundle(mockReq as Request, mockRes as Response);
    expect(mockRes.status).toHaveBeenCalledWith(500);
    expect(logger.error).toHaveBeenCalledWith('Failed to export case bundle', expect.any(Object));
  });

  it('should include correlation ID in logs', async () => {
    mockReq.headers = { 'x-correlation-id': 'test-corr' };
    (DisputeCase.find as jest.Mock).mockResolvedValue([{ _id: '123' }]);

    await exportCaseBundle(mockReq as Request, mockRes as Response);
    expect(logger.info).toHaveBeenCalledWith(expect.any(String), expect.objectContaining({ correlationId: 'test-corr' }));
  });
});
