/**
 * © 2025 CFH, All Rights Reserved
 * File: DisputeController.test.ts
 * Path: C:\CFH\backend\tests\disputes\DisputeController.test.ts
 * Purpose: Unit tests for dispute controller functions with tier-based logic and premium/Wow++ feature validation in the CFH Automotive Ecosystem.
 * Author: CFH Dev Team (generated by Grok based on Cod1 suggestions)
 * Date: 2025-07-14 [17:20]
 * Version: 1.1.0
 * Version ID: 8k9l0m1n-2o3p-4q5r-6s7t-8u9v0w1x2y3z
 * Crown Certified: Yes
 * Batch ID: Compliance-071425
 * Artifact ID: 8k9l0m1n-2o3p-4q5r-6s7t-8u9v0w1x2y3z
 * Save Location: C:\CFH\backend\tests\disputes\DisputeController.test.ts
 * Updated By: Grok (based on Cod1 suggestions)
 * Timestamp: 2025-07-14 [17:20]
 */

import { Request, Response } from 'express';
import { submitDispute } from '@controllers/dispute/DisputeController'; // Alias import
import * as disputeService from '@services/disputeService'; // Mock alias

jest.mock('@services/disputeService');

describe('Dispute Controller', () => {
  let mockReq: Partial<Request>;
  let mockRes: Partial<Response>;

  beforeEach() => {
    mockReq = { body: {}, headers: {} };
    mockRes = { status: jest.fn().mockReturnThis(), json: jest.fn() };
  });

  it('should submit a dispute with valid input', async () => {
    mockReq.body = { userId: '123e4567-e89b-12d3-a456-426614174000', listingId: 'abc', reason: 'Invalid item' };
    (disputeService.submitDispute as jest.Mock).mockResolvedValue({ _id: '123' });

    await submitDispute(mockReq as Request, mockRes as Response);
    expect(mockRes.status).toHaveBeenCalledWith(201);
    expect(mockRes.json).toHaveBeenCalledWith({ success: true, dispute: { _id: '123' } });
    expect(logger.info).toHaveBeenCalledWith('Dispute submitted', expect.any(Object));
  });

  it('should handle invalid input in submitDispute', async () => {
    mockReq.body = { userId: '123', reason: 'Short' }; // Invalid UUID, short reason

    await submitDispute(mockReq as Request, mockRes as Response);
    expect(mockRes.status).toHaveBeenCalledWith(400);
    expect(logger.error).toHaveBeenCalledWith('Dispute submission failed', expect.any(Object));
  });

  it('should handle premium evidence upload', async () => {
    mockReq.body = { ...mockReq.body, evidence: ['url1', 'url2'] }; // Premium field

    await submitDispute(mockReq as Request, mockRes as Response);
    expect(mockRes.status).toHaveBeenCalledWith(201);
    expect(mockRes.body.dispute.evidence).toBeDefined();
  });

  it('should handle Wow++ AI mediation', async () => {
    mockReq.body = { ...mockReq.body, aiMediation: true }; // Wow++ field

    await submitDispute(mockReq as Request, mockRes as Response);
    expect(mockRes.status).toHaveBeenCalledWith(201);
    expect(mockRes.body.dispute.aiMediation).toBeTrue();
  });

  it('should include correlation ID in logs', async () => {
    mockReq.headers = { 'x-correlation-id': 'test-corr' };
    mockReq.body = { userId: '123e4567-e89b-12d3-a456-426614174000', listingId: 'abc', reason: 'Invalid item' };

    await submitDispute(mockReq as Request, mockRes as Response);
    expect(logger.info).toHaveBeenCalledWith(expect.any(String), expect.objectContaining({ correlationId: 'test-corr' }));
  });
});
