/**
 * © 2025 CFH, All Rights Reserved
 * File: votingController.test.ts
 * Path: C:\CFH\backend\tests\disputes\votingController.test.ts
 * Purpose: Unit tests for voting controller functions with tier-based logic and premium/Wow++ feature validation in the CFH Automotive Ecosystem.
 * Author: CFH Dev Team (generated by Grok based on Cod1 suggestions)
 * Date: 2025-07-14 [21:50]
 * Version: 1.1.0
 * Version ID: a0b1c2d3-e4f5-g6h7-i8j9-k0l1m2n3o4p5
 * Crown Certified: Yes
 * Batch ID: Compliance-071425
 * Artifact ID: a0b1c2d3-e4f5-g6h7-i8j9-k0l1m2n3o4p5
 * Save Location: C:\CFH\backend\tests\disputes\votingController.test.ts
 * Updated By: Grok (based on Cod1 suggestions)
 * Timestamp: 2025-07-14 [21:50]
 */

import { Request, Response } from 'express';
import { voteOnDispute } from '@controllers/disputes/votingController'; // Alias import
import * as disputeVotingService from '@services/disputeVotingService'; // Mock alias
import logger from '@utils/logger'; // Spy on logger
import { UserRole } from '@utils/constants';

jest.mock('@services/disputeVotingService');
jest.spyOn(logger, 'info'); // Spy on logger.info
jest.spyOn(logger, 'error'); // Spy on logger.error

describe('Voting Controller', () => {
  let mockReq: Partial<Request>;
  let mockRes: Partial<Response>;

  beforeEach() => {
    mockReq = { body: {}, headers: {}, user: {} };
    mockRes = { status: jest.fn().mockReturnThis(), json: jest.fn() };
  });

  afterEach() => {
    jest.restoreAllMocks(); // Restore mocks to avoid contamination
  });

  it('should submit vote with valid input', async () => {
    mockReq.user = { role: UserRole.JUDGE };
    mockReq.body = { disputeId: '123e4567-e89b-12d3-a456-426614174000', userId: 'user123', voteType: 'yes' };
    (disputeVotingService.submitVote as jest.Mock).mockResolvedValue({ updated: true });

    await voteOnDispute(mockReq as Request, mockRes as Response);
    expect(mockRes.status).toHaveBeenCalledWith(201);
    expect(mockRes.json).toHaveBeenCalledWith({ success: true, result: { updated: true } });
    expect(logger.info).toHaveBeenCalledWith('Vote submitted', expect.any(Object));
  });

  it('should handle invalid input in voteOnDispute', async () => {
    mockReq.user = { role: UserRole.JUDGE };
    mockReq.body = { disputeId: 'invalid', voteType: 'invalid' }; // Invalid UUID, voteType

    await voteOnDispute(mockReq as Request, mockRes as Response);
    expect(mockRes.status).toHaveBeenCalledWith(400);
    expect(logger.error).toHaveBeenCalledWith('Failed to submit vote', expect.any(Object));
  });

  it('should restrict non-judge roles', async () => {
    mockReq.user = { role: UserRole.USER };
    mockReq.body = { disputeId: '123e4567-e89b-12d3-a456-426614174000', userId: 'user123', voteType: 'yes' };

    await voteOnDispute(mockReq as Request, mockRes as Response);
    expect(mockRes.status).toHaveBeenCalledWith(403);
    expect(mockRes.json).toHaveBeenCalledWith({ success: false, message: 'Unauthorized to vote' });
  });

  it('should include correlation ID in logs', async () => {
    mockReq.user = { role: UserRole.JUDGE };
    mockReq.headers = { 'x-correlation-id': 'test-corr' };
    mockReq.body = { disputeId: '123e4567-e89b-12d3-a456-426614174000', userId: 'user123', voteType: 'yes' };
    (disputeVotingService.submitVote as jest.Mock).mockResolvedValue({ updated: true });

    await voteOnDispute(mockReq as Request, mockRes as Response);
    expect(logger.info).toHaveBeenCalledWith(expect.any(String), expect.objectContaining({ correlationId: 'test-corr' }));
  });

  it('should handle premium weighted vote (stub)', async () => {
    mockReq.user = { role: UserRole.JUDGE };
    mockReq.body = { disputeId: '123e4567-e89b-12d3-a456-426614174000', userId: 'user123', voteType: 'yes', tier: 'premium' };
    (disputeVotingService.submitVote as jest.Mock).mockResolvedValue({ updated: true });

    await voteOnDispute(mockReq as Request, mockRes as Response);
    expect(mockRes.status).toHaveBeenCalledWith(201);
    // Stub test for weighted vote – expand when implemented
  });
});
